//
//  Actor.swift
//  ManageYourStars
//
//  Created by 陈仕鹏 on 06/09/18.
//  Copyright © 2017 csp. All rights reserved.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation
import HandyJSON

struct Actor: HandyJSON {
    var login: String?
    var display_login: String?
    var id: Int?
    var avatar_url: String?
    var url: String?
    var gravatar_id: String?

}



