//
//  Author.swift
//  ManageYourStars
//
//  Created by 陈仕鹏 on 06/09/18.
//  Copyright © 2017 csp. All rights reserved.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation
import HandyJSON


struct Author: HandyJSON {
    var name: String?
    var email: String?
    var organizations_url: String?
    var repos_url: String?
    var html_url: String?
    var site_admin: Bool?
    var gravatar_id: String?
    var starred_url: String?
    var avatar_url: String?
    var type: String?
    var gists_url: String?
    var login: String?
    var followers_url: String?
    var id: Int?
    var subscriptions_url: String?
    var following_url: String?
    var received_events_url: String?
    var node_id: String?
    var url: String?
    var events_url: String?
}



