//
//  Author.swift
//  ManageYourStars
//
//  Created by 陈仕鹏 on 06/09/18.
//  Copyright © 2017 csp. All rights reserved.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation
import HandyJSON


struct Author: HandyJSON {
    var name: String?
    var email: String?
}



