//
//  Commit.swift
//  ManageYourStars
//
//  Created by 陈仕鹏 on 06/09/18.
//  Copyright © 2017 csp. All rights reserved.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation
import HandyJSON


struct Commit: HandyJSON {
    var message: String?
    var author: Author?
    var distinct: Bool?
    var url: String?
    var sha: String?
}



