//
//  UserEvent.swift
//  ManageYourStars
//
//  Created by 陈仕鹏 on 06/09/18.
//  Copyright © 2017 csp. All rights reserved.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation
import HandyJSON


struct UserEvent: HandyJSON {
    var repo: Repo?
    var id: String?
    var created_at: String?
    var payload: Payload?
    var actor: Actor?
    var `public`: Bool?
    var type: String?

}



